### PR TITLE
Add Entity Relationship Diagrams

### PR DESCRIPTION
**Pull request by JeanDavidDaviet**
Hi, nice repo, I was beginning to work on my own mermaid in php implementation, but yours was already well advanced, and I liked the API, so I tried my hand at adding a diagram.

This PR adds the ERDiagram as documented here : 
https://mermaid.js.org/syntax/entityRelationshipDiagram.html

I tried to follow the API and coding conventions as much as I could.
I added extensive tests for each feature implemented.

Don't hesitate to give me feedback.

### CODE REVIEW

**Comment by SmetDenis** [comment]
Whoa!

This looks really awesome! Very nice work.
I'm just about ready to merge your changes and make a new version/tag.

I'm only hampered by failed autotests - https://github.com/JBZoo/Mermaid-PHP/actions/runs/6289930533

You can run all the tests locally on your machine `make test-all`
or separately unit tests with `make test` and separately to test code style `make codestyle`.
You can fix most style problems with `make test-phpcsfixer-fix`.
Thank you so much in advance.

Alternatively, I can do all these fixes myself, but it will take some time as I don't have much free time at the moment.

Thank you so much for such a great job.
It looks really great.

**Comment by JeanDavidDaviet** [comment]
No problem, I wasn't able to make the test-all command work on first time, but after a bit of playing with it, it finally worked.
I just pushed a version with the make test-all command passing. (except for the pubkeys test)

**Comment by SmetDenis** [comment]
Thank you so much. It looks great.

**Comment by JeanDavidDaviet** [comment]
That's great ! Thank you for the merge !

**Pull request merged**
