### PR TITLE
Add Timeline Diagram

### PR DESCRIPTION
**Pull request by JeanDavidDaviet**
This PR adds the Timeline as documented here :
https://mermaid.js.org/syntax/timeline.html

I tried to follow the API and coding conventions as much as I could.
I added unit tests and example of timeline in the README file

Don't hesitate to give me feedback.

### CODE REVIEW

**Comment by SmetDenis** [comment]
Whoa!

This looks really awesome! Very nice work.
I'm just about ready to merge your changes and make a new version/tag.

I'm only hampered by failed autotests - https://github.com/JBZoo/Mermaid-PHP/actions/runs/6290230953

You can run all the tests locally on your machine `make test-all`
or separately unit tests with `make test` and separately to test code style `make codestyle`.
You can fix most style problems with `make test-phpcsfixer-fix`.
Thank you so much in advance.

Alternatively, I can do all these fixes myself, but it will take some time as I don't have much free time at the moment.

Thank you so much for such a great job.
It looks really great.

**Comment by JeanDavidDaviet** [comment]
No problem, I wasn't able to make the test-all command work on first time, but after a bit of playing with it, it finally worked.
I just pushed a version with the make test-all command passing. (except for the pubkeys test)

**Comment by SmetDenis** [comment]
Thank you. All tests are passed.
I can approve it.

I merged your recent PR https://github.com/JBZoo/Mermaid-PHP/pull/14
and I can see a few merge conflicts.
 * README.md
 * src/Helper.php
 * src/Render.php

Can you please take a look at them?

I really appreciate any help you can provide.

**Comment by JeanDavidDaviet** [comment]
Yes, I was expecting some conflict as I was reusing the Helper and Render class with only changing the Union type Graph for Graph|Timeline.
As I worked on both PR at the same time it was going to happen.
It's fixed

**Comment by SmetDenis** [comment]
> Yes, I was expecting some conflict as I was reusing the Helper and Render class with only changing the Union type Graph for Graph|Timeline. As I worked on both PR at the same time it was going to happen. It's fixed

Thank you. It looks much better.

Just a few questions.
* Do we really need [index.php](https://github.com/JeanDavidDaviet/mermaid-php/blob/add-timeline/index.php) file?
* I guess you removed your recent changes in Readme file, right?

**Comment by JeanDavidDaviet** [comment]
Good catch ! I think I failed during the rebase.
It's should be all good now :)

**Comment by SmetDenis** [comment]
Awesome. It looks perfect!
Huge thank you for your help.

**Pull request merged**
